version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: testdb
          - DB_USERNAME: root
    steps:
      - run: echo "Hello World" #==========この行を削除
      #==========ここから追加==========
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: ./vendor/bin/phpunit

          