version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE: testdb
          - MYSQL_ROOT_PASSWORD: root
    environment:
      - DB_HOST: 127.0.0.1
    steps:
      #==========ここから追加==========
      - checkout
      - restore_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
        paths:
          - vendor
      - run: sudo apt update 
      - run: sudo apt-get install -y libpng-dev libjpeg-dev
      - run: sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo docker-php-ext-install gd
      - run: sudo composer self-update --1
      
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: ./vendor/bin/phpunit

          