version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE: testdb
          - MYSQL_ROOT_PASSWORD: root
    environment:
      - DB_HOST: 127.0.0.1
    steps:
      - run: echo "Hello World" #==========この行を削除
      #==========ここから追加==========
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install libfreetype6-dev
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/freetype2/
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo docker-php-ext-install intl gd
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: ./vendor/bin/phpunit

          